
- name: Say Hello
  shell: pwsh
  run: |
    # Allow PowerShell scripts to run temporarily
    Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force
    Write-Output "Hello from self-hosted runner"
    # If you have a PowerShell script file, run it like this:
    # ./_work/temp/3100-leal-ebe5-4ole-6744-67ba9cfc90eb.ps1
